[package]
name = "nn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra-glm = "0.18.0"
nalgebra = { version = "0.32.2", features = ["rand"] }
libm = "0.2.6"
polars = { version = "0.28.0", features = ["lazy"] }
plotters = "0.3.4"
rand = "0.8.5"
serde = { version = "1.0.159", features = ["derive"] }