[package]
name = "xor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "*"
neural_networks_rust = { path = "../../" }
plotters = "0.3.4"