[package]
name = "housing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nn = { path = "../../" }
polars = { version = "0.28.0", features = ["lazy"] }
plotly = { version = "0.8.3", features = ["kaleido"] }
rand = "0.8.5"
serde = { version = "1.0.159", features = ["derive"]}
serde_json = "1.0.95"
chrono = "0.4.24"